mkdir -p build
cd build
rm -rf *

LIB_DIR=$1
DEMO_NAME=$2
MODEL_FILE_DIR=$3
WITH_GPU=$4
CUDNN_LIB=$5
CUDA_LIB=$6
CUSTOM_OPERATOR_FILES=$7
DP_LIB_DIR=$8
BOOST_DIR=$9
cmake .. -DPADDLE_LIB=${LIB_DIR} \
  -DDEMO_NAME=${DEMO_NAME} \
  -DWITH_GPU=${WITH_GPU} \
  -DWITH_STATIC_LIB=OFF \
  -DCUDNN_LIB=${CUDNN_LIB} \
  -DCUDA_LIB=${CUDA_LIB} \
  -DCUSTOM_OPERATOR_FILES=${CUSTOM_OPERATOR_FILES}\
  -DDP_LIB_DIR=${DP_LIB_DIR}\
  -DBOOST_DIR=${BOOST_DIR}

make -j

cp ${DEMO_NAME} ../
#cp -rf ${MODEL_FILE_DIR} ./
#./${DEMO_NAME}
